Traceback (most recent call last):
  File "/home/edu/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/edu/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/edu/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/edu/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/edu/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/edu/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/edu/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/edu/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numpy import *
from matplotlib.pyplot import *
style.use('fivethirtyeight')
delta = arange(0,6*pi,0.1)
## Cambia estos parametros
I_1 = 1
I_2 =  0.2
############
I_t = I_1 + I_2 + 2*sqrt(I_1*I_2)*cos(delta)
fig = plt.figure(figsize=(10,6))
plot(delta,I_t)
ylim(0,4)
xlabel(r'$\delta$')
ylabel(r'I$_t$');
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1932683/534213191.py[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m [0;31m############[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0mI_t[0m [0;34m=[0m [0mI_1[0m [0;34m+[0m [0mI_2[0m [0;34m+[0m [0;36m2[0m[0;34m*[0m[0msqrt[0m[0;34m([0m[0mI_1[0m[0;34m*[0m[0mI_2[0m[0;34m)[0m[0;34m*[0m[0mcos[0m[0;34m([0m[0mdelta[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m [0mfig[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m10[0m[0;34m,[0m[0;36m6[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0mplot[0m[0;34m([0m[0mdelta[0m[0;34m,[0m[0mI_t[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0mylim[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'plt' is not defined
NameError: name 'plt' is not defined

